package com.fph.lotteryanalyze.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fph.lotteryanalyze.db.OmitEntity;
import com.fph.lotteryanalyze.db.DltLotteryEntity;
import com.fph.lotteryanalyze.db.LotteryEntity;
import com.fph.lotteryanalyze.db.BallEntity;
import com.fph.lotteryanalyze.db.ArrangeThreeEntity;
import com.fph.lotteryanalyze.db.ETCFBean;

import com.fph.lotteryanalyze.db.OmitEntityDao;
import com.fph.lotteryanalyze.db.DltLotteryEntityDao;
import com.fph.lotteryanalyze.db.LotteryEntityDao;
import com.fph.lotteryanalyze.db.BallEntityDao;
import com.fph.lotteryanalyze.db.ArrangeThreeEntityDao;
import com.fph.lotteryanalyze.db.ETCFBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig omitEntityDaoConfig;
    private final DaoConfig dltLotteryEntityDaoConfig;
    private final DaoConfig lotteryEntityDaoConfig;
    private final DaoConfig ballEntityDaoConfig;
    private final DaoConfig arrangeThreeEntityDaoConfig;
    private final DaoConfig eTCFBeanDaoConfig;

    private final OmitEntityDao omitEntityDao;
    private final DltLotteryEntityDao dltLotteryEntityDao;
    private final LotteryEntityDao lotteryEntityDao;
    private final BallEntityDao ballEntityDao;
    private final ArrangeThreeEntityDao arrangeThreeEntityDao;
    private final ETCFBeanDao eTCFBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        omitEntityDaoConfig = daoConfigMap.get(OmitEntityDao.class).clone();
        omitEntityDaoConfig.initIdentityScope(type);

        dltLotteryEntityDaoConfig = daoConfigMap.get(DltLotteryEntityDao.class).clone();
        dltLotteryEntityDaoConfig.initIdentityScope(type);

        lotteryEntityDaoConfig = daoConfigMap.get(LotteryEntityDao.class).clone();
        lotteryEntityDaoConfig.initIdentityScope(type);

        ballEntityDaoConfig = daoConfigMap.get(BallEntityDao.class).clone();
        ballEntityDaoConfig.initIdentityScope(type);

        arrangeThreeEntityDaoConfig = daoConfigMap.get(ArrangeThreeEntityDao.class).clone();
        arrangeThreeEntityDaoConfig.initIdentityScope(type);

        eTCFBeanDaoConfig = daoConfigMap.get(ETCFBeanDao.class).clone();
        eTCFBeanDaoConfig.initIdentityScope(type);

        omitEntityDao = new OmitEntityDao(omitEntityDaoConfig, this);
        dltLotteryEntityDao = new DltLotteryEntityDao(dltLotteryEntityDaoConfig, this);
        lotteryEntityDao = new LotteryEntityDao(lotteryEntityDaoConfig, this);
        ballEntityDao = new BallEntityDao(ballEntityDaoConfig, this);
        arrangeThreeEntityDao = new ArrangeThreeEntityDao(arrangeThreeEntityDaoConfig, this);
        eTCFBeanDao = new ETCFBeanDao(eTCFBeanDaoConfig, this);

        registerDao(OmitEntity.class, omitEntityDao);
        registerDao(DltLotteryEntity.class, dltLotteryEntityDao);
        registerDao(LotteryEntity.class, lotteryEntityDao);
        registerDao(BallEntity.class, ballEntityDao);
        registerDao(ArrangeThreeEntity.class, arrangeThreeEntityDao);
        registerDao(ETCFBean.class, eTCFBeanDao);
    }
    
    public void clear() {
        omitEntityDaoConfig.clearIdentityScope();
        dltLotteryEntityDaoConfig.clearIdentityScope();
        lotteryEntityDaoConfig.clearIdentityScope();
        ballEntityDaoConfig.clearIdentityScope();
        arrangeThreeEntityDaoConfig.clearIdentityScope();
        eTCFBeanDaoConfig.clearIdentityScope();
    }

    public OmitEntityDao getOmitEntityDao() {
        return omitEntityDao;
    }

    public DltLotteryEntityDao getDltLotteryEntityDao() {
        return dltLotteryEntityDao;
    }

    public LotteryEntityDao getLotteryEntityDao() {
        return lotteryEntityDao;
    }

    public BallEntityDao getBallEntityDao() {
        return ballEntityDao;
    }

    public ArrangeThreeEntityDao getArrangeThreeEntityDao() {
        return arrangeThreeEntityDao;
    }

    public ETCFBeanDao getETCFBeanDao() {
        return eTCFBeanDao;
    }

}
