package com.fph.lotteryanalyze.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOTTERY_ENTITY".
*/
public class LotteryEntityDao extends AbstractDao<LotteryEntity, Long> {

    public static final String TABLENAME = "LOTTERY_ENTITY";

    /**
     * Properties of entity LotteryEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Expect = new Property(1, String.class, "expect", false, "EXPECT");
        public final static Property Opencode = new Property(2, String.class, "opencode", false, "OPENCODE");
        public final static Property Opentime = new Property(3, String.class, "opentime", false, "OPENTIME");
        public final static Property Opentimestamp = new Property(4, Long.class, "opentimestamp", false, "OPENTIMESTAMP");
    }


    public LotteryEntityDao(DaoConfig config) {
        super(config);
    }
    
    public LotteryEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOTTERY_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"EXPECT\" TEXT UNIQUE ," + // 1: expect
                "\"OPENCODE\" TEXT," + // 2: opencode
                "\"OPENTIME\" TEXT," + // 3: opentime
                "\"OPENTIMESTAMP\" INTEGER);"); // 4: opentimestamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOTTERY_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LotteryEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String expect = entity.getExpect();
        if (expect != null) {
            stmt.bindString(2, expect);
        }
 
        String opencode = entity.getOpencode();
        if (opencode != null) {
            stmt.bindString(3, opencode);
        }
 
        String opentime = entity.getOpentime();
        if (opentime != null) {
            stmt.bindString(4, opentime);
        }
 
        Long opentimestamp = entity.getOpentimestamp();
        if (opentimestamp != null) {
            stmt.bindLong(5, opentimestamp);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LotteryEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String expect = entity.getExpect();
        if (expect != null) {
            stmt.bindString(2, expect);
        }
 
        String opencode = entity.getOpencode();
        if (opencode != null) {
            stmt.bindString(3, opencode);
        }
 
        String opentime = entity.getOpentime();
        if (opentime != null) {
            stmt.bindString(4, opentime);
        }
 
        Long opentimestamp = entity.getOpentimestamp();
        if (opentimestamp != null) {
            stmt.bindLong(5, opentimestamp);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LotteryEntity readEntity(Cursor cursor, int offset) {
        LotteryEntity entity = new LotteryEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // expect
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // opencode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // opentime
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // opentimestamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LotteryEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setExpect(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOpencode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOpentime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOpentimestamp(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LotteryEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LotteryEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LotteryEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
